import ReactQueryProvider from '@/providers/ReactQueryProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import { Provider } from './provider'
const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Spenxo',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" data-theme="mytheme">
      {/* <Provider> */}
        <body className={inter.className}>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </body>
      {/* </Provider> */}
    </html>
  )
}